apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels: 
    project: roboshop
    component: shipping
    tier: backend
spec:
  replicas: 1
  selector: 
    matchLabels:
      project: roboshop
      component: shipping
      tier: backend    
  template:
    metadata:
      labels:
        project: roboshop
        component: shipping
        tier: backend
    spec:
      containers:
      - name: shipping
        image: "{{ .Values.deployment.imageRepo }}:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 100
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 100
  
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: liveness-port
        #   failureThreshold: 6
        #   periodSeconds: 20
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: liveness-port
        #   failureThreshold: 6
        #   periodSeconds: 20

---

apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  type: {{ .Values.service.type }}
  selector:
    project: roboshop
    component: shipping
    tier: backend
  ports:
  - protocol: TCP
    port: {{ .Values.service.servicePort }} # service port
    targetPort: 8080 # container port 